version: "3"

services:
    pypiserver:
        container_name: pypiserver
        image: pypiserver-image:latest
        build:
            context: .
        ports:
            - 31415:31415
        volumes:
            - ~/packages:/root/packages
            - /etc/localtime:/etc/localtime
